import type {
  BjjAchievement,
  BjjChallenge,
  BjjChecklistItem,
  BjjFeedPost,
  BjjLeaderboardEntry,
  BjjNotification,
  BjjOnboardingStep,
  BjjPaywallStep,
  BjjPersistedState,
  BjjSuggestedGrappler,
  BjjSystem,
  BjjTechnique,
  BjjTechniqueCategory,
} from '@/lib/bjj-types'
import { MARTIAL_ARTS_BRANCHES } from '@/lib/martial-arts-branches'

export const BJJ_STORAGE_KEY = 'matflow.v2'

export const BJJ_ONBOARDING_STEPS: BjjOnboardingStep[] = [
  'welcome',
  'mission',
  'name',
  'discipline',
  'experience',
  'content',
  'pain-points',
  'attribution',
  'setup',
  'ready',
]

export const BJJ_PAYWALL_STEPS: BjjPaywallStep[] = ['founder', 'pro', 'trial', 'pricing']

export const BJJ_CHALLENGE_OPTIONS = [
  "Can't remember techniques",
  "Feel like I'm not progressing",
  'Training feels scattered',
  'Getting beat by the same people / same technique',
  "Not sure what my gameplan should be",
] as const

export const BJJ_HEARD_FROM_OPTIONS = ['Friends', 'Instagram', 'App Store', 'Google'] as const

export const BJJ_PRIMARY_DISCIPLINE_OPTIONS = MARTIAL_ARTS_BRANCHES.map((branch) => branch.label)

export const BJJ_EXPERIENCE_LEVEL_OPTIONS = [
  {
    id: 'white-beginner',
    experienceLevel: 'beginner',
    label: 'White belt / Beginner',
    belt: 'white',
    stripes: 0,
  },
  {
    id: 'blue-intermediate',
    experienceLevel: 'intermediate',
    label: 'Blue belt / Intermediate',
    belt: 'blue',
    stripes: 0,
  },
  {
    id: 'purple-advanced',
    experienceLevel: 'advanced',
    label: 'Purple belt / Advanced',
    belt: 'purple',
    stripes: 0,
  },
  {
    id: 'brown-black-pro',
    experienceLevel: 'advanced',
    label: 'Brown / Black belt / Pro',
    belt: 'brown',
    stripes: 0,
  },
] as const

export const BJJ_FAVORITE_CONTENT_OPTIONS = [
  'Technique breakdowns',
  'Live rolling / sparring analysis',
  'Drill libraries',
  'Fight study & analysis',
  'Strength & conditioning for fighters',
  'Mental game and strategy',
] as const

export const BJJ_CATEGORY_META: Record<BjjTechniqueCategory, { label: string; count: number; color: string }> = {
  submission: { label: 'Submission', count: 24, color: '#ef4444' },
  sweep: { label: 'Sweep', count: 12, color: '#f59e0b' },
  escape: { label: 'Escape', count: 10, color: '#eab308' },
  'guard-pass': { label: 'Guard Pass', count: 9, color: '#22c55e' },
  takedown: { label: 'Takedown', count: 12, color: '#38bdf8' },
  transition: { label: 'Transition', count: 10, color: '#3b82f6' },
  strike: { label: 'Strike', count: 18, color: '#fb7185' },
  defense: { label: 'Defense', count: 16, color: '#14b8a6' },
  footwork: { label: 'Footwork', count: 10, color: '#a855f7' },
  clinch: { label: 'Clinch', count: 12, color: '#f97316' },
  kick: { label: 'Kick', count: 14, color: '#84cc16' },
  counter: { label: 'Counter', count: 10, color: '#06b6d4' },
}

const now = new Date().toISOString()

export const DISCOVER_TECHNIQUES: BjjTechnique[] = [
  {
    id: 'disc-scissor-sweep',
    branch: 'bjj',
    title: 'Scissor Sweep',
    category: 'sweep',
    tags: ['Closed Guard', 'Fundamental'],
    notes: '',
    description: 'A fundamental closed guard sweep using opposite leg movement to break posture and tip the opponent forward.',
    tutorialTitle: 'These Details Make It Work',
    media: [],
    links: ['https://www.youtube.com/watch?v=scissor-sweep'],
    linkedTechniqueIds: ['disc-triangle-choke'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-triangle-choke',
    branch: 'bjj',
    title: 'Triangle Choke',
    category: 'submission',
    tags: ['Submission', 'Beginner', 'Closed Guard'],
    notes: '',
    description: 'A guard staple that punishes posture mistakes and chains naturally from collar tie, arm drag, and scissor sweep threats.',
    tutorialTitle: 'Triangle From Broken Posture',
    media: [],
    links: ['https://www.youtube.com/watch?v=triangle-choke'],
    linkedTechniqueIds: ['disc-scissor-sweep'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-armbar',
    branch: 'bjj',
    title: 'Armbar',
    category: 'submission',
    tags: ['Submission', 'Beginner'],
    notes: '',
    description: 'Classic arm isolation finish that rewards good angle changes and tight leg positioning.',
    tutorialTitle: 'Armbar Control Principles',
    media: [],
    links: ['https://www.youtube.com/watch?v=armbar'],
    linkedTechniqueIds: ['disc-triangle-choke'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-rear-naked-choke',
    branch: 'bjj',
    title: 'Rear Naked Choke',
    category: 'submission',
    tags: ['Submission', 'Back Control'],
    notes: '',
    description: 'The highest percentage finishing sequence from the back when your harness and hand fighting are disciplined.',
    tutorialTitle: 'Back Control Finishing Details',
    media: [],
    links: ['https://www.youtube.com/watch?v=rear-naked-choke'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-kimura',
    branch: 'bjj',
    title: 'Kimura',
    category: 'submission',
    tags: ['Submission', 'Shoulder Lock'],
    notes: '',
    description: 'Strong upper-body control attack from guard, side control, and turtle with excellent sweep chains.',
    tutorialTitle: 'Kimura Trap Essentials',
    media: [],
    links: ['https://www.youtube.com/watch?v=kimura'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-hip-bump-sweep',
    branch: 'bjj',
    title: 'Hip Bump Sweep',
    category: 'sweep',
    tags: ['Closed Guard', 'Sit-Up'],
    notes: '',
    description: 'Momentum-based sweep that forces a post and opens up kimura and guillotine follow-ups.',
    tutorialTitle: 'Hip Bump Timing',
    media: [],
    links: ['https://www.youtube.com/watch?v=hip-bump-sweep'],
    linkedTechniqueIds: ['disc-kimura'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-side-control-frame-escape',
    branch: 'bjj',
    title: 'Side Control Frame Escape',
    category: 'escape',
    tags: ['Escape', 'No-Gi', 'Side Control'],
    notes: '',
    description: 'Frame, hip escape, and knee-insertion sequence for rebuilding guard before the crossface settles.',
    tutorialTitle: 'Frames That Actually Work',
    media: [],
    links: ['https://www.youtube.com/watch?v=side-control-escape'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-double-leg',
    branch: 'wrestling',
    title: 'Double Leg',
    category: 'takedown',
    tags: ['Wrestling', 'Fundamental'],
    notes: '',
    description: 'Level change, penetration step, and corner finish mechanics for reliable takedown entries.',
    tutorialTitle: 'Double Leg Finishing',
    media: [],
    links: ['https://www.youtube.com/watch?v=double-leg'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-knee-cut',
    branch: 'bjj',
    title: 'Knee Cut Pass',
    category: 'guard-pass',
    tags: ['Guard Pass', 'Pressure'],
    notes: '',
    description: 'Reliable passing sequence when you win the inside knee line and flatten the bottom player.',
    tutorialTitle: 'Knee Cut Pressure',
    media: [],
    links: ['https://www.youtube.com/watch?v=knee-cut'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-arm-drag',
    branch: 'grappling',
    title: 'Arm Drag',
    category: 'transition',
    tags: ['Transition', 'Back Take'],
    notes: '',
    description: 'Connection-based transition that turns a winning grip into angles, back exposure, or sweeps.',
    tutorialTitle: 'Arm Drag Connections',
    media: [],
    links: ['https://www.youtube.com/watch?v=arm-drag'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-grappling-front-headlock',
    branch: 'grappling',
    title: 'Front Headlock Snapdown',
    category: 'takedown',
    tags: ['No-Gi', 'Front Headlock', 'Control'],
    notes: '',
    description: 'A snapdown entry that pulls posture forward and opens go-behind, guillotine, or spin-behind routes.',
    tutorialTitle: 'Front Headlock Control',
    media: [],
    links: ['https://www.youtube.com/watch?v=front-headlock'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-boxing-jab',
    branch: 'boxing',
    title: 'Lead Jab',
    category: 'strike',
    tags: ['Range', 'Setup', 'Fundamental'],
    notes: '',
    description: 'Straight lead-hand punch used to measure distance, interrupt entries, and build combinations.',
    tutorialTitle: 'Jab Mechanics',
    media: [],
    links: ['https://www.youtube.com/watch?v=boxing-jab'],
    linkedTechniqueIds: ['disc-boxing-cross'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-boxing-cross',
    branch: 'boxing',
    title: 'Rear Cross',
    category: 'strike',
    tags: ['Power', 'Straight Punch', 'Combination'],
    notes: '',
    description: 'Rear-hand straight built from hip rotation, shoulder cover, and balanced recovery.',
    tutorialTitle: 'Cross Without Overreaching',
    media: [],
    links: ['https://www.youtube.com/watch?v=boxing-cross'],
    linkedTechniqueIds: ['disc-boxing-lead-hook'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-boxing-lead-hook',
    branch: 'boxing',
    title: 'Lead Hook',
    category: 'strike',
    tags: ['Inside Range', 'Combination', 'Power'],
    notes: '',
    description: 'Compact hook that turns the lead side through the target without drifting past stance.',
    tutorialTitle: 'Lead Hook Alignment',
    media: [],
    links: ['https://www.youtube.com/watch?v=lead-hook'],
    linkedTechniqueIds: ['disc-boxing-slip-outside'],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-boxing-slip-outside',
    branch: 'boxing',
    title: 'Outside Slip',
    category: 'defense',
    tags: ['Head Movement', 'Counter', 'Defense'],
    notes: '',
    description: 'Small outside head movement that keeps stance loaded for the cross or pivot exit.',
    tutorialTitle: 'Slip And Counter',
    media: [],
    links: ['https://www.youtube.com/watch?v=outside-slip'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-boxing-pivot-exit',
    branch: 'boxing',
    title: 'Lead Foot Pivot Exit',
    category: 'footwork',
    tags: ['Angle', 'Exit', 'Defense'],
    notes: '',
    description: 'Angle change after a combination to leave the center line instead of admiring the work.',
    tutorialTitle: 'Pivot Exit After Contact',
    media: [],
    links: ['https://www.youtube.com/watch?v=pivot-exit'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-muay-thai-teep',
    branch: 'muay-thai',
    title: 'Lead Teep',
    category: 'kick',
    tags: ['Range', 'Interruption', 'Balance'],
    notes: '',
    description: 'Front push kick that manages distance and interrupts forward pressure.',
    tutorialTitle: 'Lead Teep Balance',
    media: [],
    links: ['https://www.youtube.com/watch?v=lead-teep'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-muay-thai-clinch-knee',
    branch: 'muay-thai',
    title: 'Double Collar Knee',
    category: 'clinch',
    tags: ['Clinch', 'Knee', 'Posture'],
    notes: '',
    description: 'Posture-breaking collar tie sequence into balanced knees without pulling yourself off stance.',
    tutorialTitle: 'Clinch Knee Control',
    media: [],
    links: ['https://www.youtube.com/watch?v=clinch-knee'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-wrestling-sprawl',
    branch: 'wrestling',
    title: 'Sprawl And Crossface',
    category: 'defense',
    tags: ['Shot Defense', 'Pressure', 'Fundamental'],
    notes: '',
    description: 'Hip-heavy shot defense that turns penetration steps into front-headlock pressure.',
    tutorialTitle: 'Sprawl Timing',
    media: [],
    links: ['https://www.youtube.com/watch?v=sprawl-crossface'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
  {
    id: 'disc-judo-osoto-gari',
    branch: 'judo',
    title: 'Osoto Gari',
    category: 'takedown',
    tags: ['Throw', 'Off-Balance', 'Gi'],
    notes: '',
    description: 'Major outer reap built from kuzushi, chest pressure, and a committed reaping leg.',
    tutorialTitle: 'Osoto Gari Entries',
    media: [],
    links: ['https://www.youtube.com/watch?v=osoto-gari'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'discover',
  },
]

export const SEED_LIBRARY_TECHNIQUES: BjjTechnique[] = [
  {
    id: 'lib-triangle-choke',
    branch: 'bjj',
    title: 'Triangle Choke',
    category: 'submission',
    tags: ['Submission', 'Beginner', 'Closed Guard'],
    notes: 'Break posture first. Angle off before closing the figure-four.',
    description: 'Closed guard triangle with posture break, shin across the neck, and hip angle before locking.',
    tutorialTitle: 'Triangle Choke Mechanics',
    media: [],
    links: ['https://www.youtube.com/watch?v=triangle-choke'],
    linkedTechniqueIds: [],
    createdAt: now,
    updatedAt: now,
    ownership: 'library',
  },
]

export const SEED_SUGGESTED_GRAPPLERS: BjjSuggestedGrappler[] = [
  { id: 'alex', name: 'Alex', handle: '@alexguard', accent: '#2563eb', branch: 'bjj', branchLabel: 'BJJ' },
  { id: 'diego', name: 'Diego', handle: '@diegohooks', accent: '#7c3aed', branch: 'grappling', branchLabel: 'Grappling' },
  { id: 'chris', name: 'Chris', handle: '@chrispressure', accent: '#0ea5e9', branch: 'boxing', branchLabel: 'Boxing' },
]

export const SEED_FEED_POSTS: BjjFeedPost[] = [
  {
    id: 'post-1',
    authorName: 'Dawson',
    authorHandle: '@dawsonwrestles',
    title: 'Competition @ Jitzking',
    summary: 'Signed up for the adult absolute cash prize division and finally got to test the gameplan under pressure.',
    submissions: 0,
    durationLabel: '1h 45m',
    imageLabel: 'Competition match photo',
    createdAtLabel: '1 day ago',
    likes: 12,
    comments: 3,
    saves: 0,
    likedByViewer: false,
    savedByViewer: false,
    accent: '#3b82f6',
    source: 'session',
  },
  {
    id: 'post-2',
    authorName: 'Kait Cox',
    authorHandle: '@kaittriangle',
    title: 'Open Mat Notes',
    summary: 'Spent the whole round cycle forcing scissor sweep to triangle. Notes are finally getting cleaner.',
    submissions: 2,
    durationLabel: '58m',
    imageLabel: 'Open mat screenshot card',
    createdAtLabel: '3 days ago',
    likes: 24,
    comments: 5,
    saves: 0,
    likedByViewer: false,
    savedByViewer: false,
    accent: '#2563eb',
    source: 'session',
  },
]

export const SEED_NOTIFICATIONS: BjjNotification[] = []

export const SEED_CHALLENGES: BjjChallenge[] = [
  {
    id: 'challenge-warrior',
    title: 'Weekly Warrior',
    summary: 'Complete 3 training sessions this week.',
    progress: 0,
    goal: 3,
    xpReward: 50,
    difficulty: 'beginner',
  },
  {
    id: 'challenge-collector',
    title: 'Dedicated Practitioner',
    summary: 'Save 5 techniques to your library.',
    progress: 1,
    goal: 5,
    xpReward: 100,
    difficulty: 'beginner',
  },
]

export const SEED_ACHIEVEMENTS: BjjAchievement[] = [
  {
    id: 'ach-first-session',
    title: 'Showed Up',
    summary: 'Log your first training session.',
    progress: 0,
    goal: 1,
  },
  {
    id: 'ach-technique-web',
    title: 'System Builder',
    summary: 'Link 10 techniques together.',
    progress: 0,
    goal: 10,
  },
]

export const createChecklistItems = (
  sessionsCount: number,
  techniquesCount: number,
  hasPublicPost: boolean
): BjjChecklistItem[] => [
  {
    id: 'check-session',
    title: 'Log your next session',
    summary: 'Turn every class into useful feedback instead of vague memory.',
    completed: sessionsCount > 0,
  },
  {
    id: 'check-techniques',
    title: 'Save 3 core techniques',
    summary: 'Start with moves you actually hit or get caught by.',
    completed: techniquesCount >= 3,
  },
  {
    id: 'check-share',
    title: 'Share one public update',
    summary: 'Build accountability and let training partners follow the arc.',
    completed: hasPublicPost,
  },
]

export const SEED_LEADERBOARD: BjjLeaderboardEntry[] = [
  { id: 'rank-1', name: 'Jax', handle: '@ronin_nomad', score: 696 },
  { id: 'rank-2', name: 'Darmin', handle: '@grappler_747a9ee5', score: 582 },
  { id: 'rank-3', name: 'Edoardo', handle: '@aleiactaest', score: 318 },
  { id: 'rank-4', name: 'abdulrahman', handle: '@abdulrahman', score: 302 },
  { id: 'rank-5', name: 'Justin', handle: '@coldinero', score: 297 },
  { id: 'rank-6', name: 'Elijah', handle: '@elijahlovesbjj', score: 274 },
  { id: 'rank-7', name: 'Nacho', handle: '@nacho', score: 248 },
  { id: 'rank-8', name: 'Marcc', handle: '@grappler_78ceec71', score: 239 },
]

export const SEED_SYSTEMS: BjjSystem[] = [
  {
    id: 'system-closed-guard',
    branch: 'bjj',
    title: 'Closed Guard Attacks',
    summary: 'Scissor sweep into triangle, armbar, and hip bump reactions.',
    nodes: [
      { id: 'node-posture', label: 'Break Posture', color: '#3b82f6' },
      { id: 'node-sweep', label: 'Scissor Sweep', color: '#22c55e' },
      { id: 'node-triangle', label: 'Triangle', color: '#ef4444' },
      { id: 'node-armbar', label: 'Armbar', color: '#f59e0b' },
    ],
    edges: [
      { from: 'node-posture', to: 'node-sweep' },
      { from: 'node-posture', to: 'node-triangle' },
      { from: 'node-triangle', to: 'node-armbar' },
    ],
  },
  {
    id: 'system-back-control',
    branch: 'bjj',
    title: 'Back Control Funnels',
    summary: 'Hand fight, trap the shoulder line, then route to RNC or bow-and-arrow.',
    nodes: [
      { id: 'node-seatbelt', label: 'Seatbelt', color: '#3b82f6' },
      { id: 'node-handfight', label: 'Hand Fight', color: '#a855f7' },
      { id: 'node-rnc', label: 'RNC', color: '#ef4444' },
      { id: 'node-switch', label: 'Bow & Arrow', color: '#22c55e' },
    ],
    edges: [
      { from: 'node-seatbelt', to: 'node-handfight' },
      { from: 'node-handfight', to: 'node-rnc' },
      { from: 'node-handfight', to: 'node-switch' },
    ],
    locked: true,
  },
]

export function createDefaultBjjState(displayName = 'Grappler', username = 'grappler'): BjjPersistedState {
  return {
    profile: {
      displayName,
      username,
      belt: 'white',
      stripes: 0,
      gymName: '',
      bio: '',
      privacy: 'public',
      xp: 50,
      level: 1,
      flowStreak: 1,
      trainingStreak: 0,
      primaryDiscipline: undefined,
      experienceLevel: undefined,
      favoriteContentTypes: [],
      biggestChallenges: [],
      onboardingCompleted: false,
      paywallCompleted: false,
      coachMarksSeen: false,
      proUnlocked: false,
    },
    selectedBottomTab: 'today',
    selectedSessionsTab: 'my-sessions',
    selectedTechniquesTab: 'my-library',
    socialSurface: 'bjj',
    socialHomeRail: 'for_you',
    selectedTechniqueBranch: 'bjj',
    selectedSystemBranch: 'bjj',
    librarySort: 'new',
    activeCategoryFilter: 'all',
    searchQuery: '',
    customTags: [],
    libraryTechniques: [],
    discoverAddedTechniqueIds: [],
    sessions: [],
    followedGrapplerIds: [],
    likedPostIds: [],
    notifications: SEED_NOTIFICATIONS,
    systemsHubFilter: 'all',
    systemsHubSearch: '',
    pinnedSystemIds: [],
  }
}
