import { BJJ_CATEGORY_META } from '@/lib/bjj-seed'
import type { BjjTechniqueCategory } from '@/lib/bjj-types'

export function slugifyUsername(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
}

export function isAutoGeneratedUsername(username: string): boolean {
  const u = username.trim().toLowerCase()
  return (
    u === ''
    || u === 'grappler'
    || u.startsWith('grappler_')
    || u.startsWith('user_')
  )
}

export async function readVideoMetadata(
  file: File,
): Promise<{ previewUrl: string; durationMs: number; aspectRatio: number }> {
  const previewUrl = URL.createObjectURL(file)

  return await new Promise((resolve, reject) => {
    const video = document.createElement('video')
    video.preload = 'metadata'
    video.src = previewUrl
    video.onloadedmetadata = () => {
      const durationMs = Math.round((video.duration || 0) * 1000)
      const width = video.videoWidth || 0
      const height = video.videoHeight || 0
      resolve({
        previewUrl,
        durationMs,
        aspectRatio: width > 0 && height > 0 ? width / height : 9 / 16,
      })
    }
    video.onerror = () => {
      URL.revokeObjectURL(previewUrl)
      reject(new Error('Unable to read this video file'))
    }
  })
}

export function formatDurationSeconds(valueMs: number): string {
  return `${Math.max(0, Math.round(valueMs / 1000))}s`
}

export function toTechniqueColor(category: BjjTechniqueCategory): string {
  return BJJ_CATEGORY_META[category].color
}

