'use client'

import Image from 'next/image'
import { BookOpen, Check, ChevronLeft, ChevronRight, Star } from 'lucide-react'
import {
  BJJ_CHALLENGE_OPTIONS,
  BJJ_EXPERIENCE_LEVEL_OPTIONS,
  BJJ_FAVORITE_CONTENT_OPTIONS,
  BJJ_HEARD_FROM_OPTIONS,
  BJJ_ONBOARDING_STEPS,
  BJJ_PRIMARY_DISCIPLINE_OPTIONS,
} from '@/lib/bjj-seed'
import { resolveOnboardingDisplayNameDraft } from '@/lib/bjj-state'
import type { BjjOnboardingStep, BjjPersistedState } from '@/lib/bjj-types'
import { createDisplayNameInputBehavior, shouldIgnoreDisplayNameRefill } from '@/lib/display-name-input'
import type { UserProfile } from '@/lib/user-profile-types'
import { cn } from '@/lib/utils'
import { isAutoGeneratedUsername, slugifyUsername } from './format-utils'
import { CircleIconButton, PrimaryButton, ProgressDots, ShellCard } from './primitives'
import { ScreenBackdrop, type ScreenBackdropVariant } from './screen-backdrop'
import type { NativeInputLike } from './types'

export interface OnboardingScreenProps {
  appState: BjjPersistedState
  updateAppState: (updater: (previous: BjjPersistedState) => BjjPersistedState) => void
  updateProfile: (updates: Partial<UserProfile>) => Promise<UserProfile>
  refreshShellSnapshot: () => void
  onboardingIndex: number
  setOnboardingIndex: (updater: number | ((previous: number) => number)) => void
  onboardingNameDraft: string
  setOnboardingNameDraft: (value: string) => void
  onboardingNameDirty: boolean
  setOnboardingNameDirty: (value: boolean) => void
  onboardingNameSentinel: string
  onboardingNameInputUnlocked: boolean
  setOnboardingNameInputUnlocked: (value: true) => void
  setupProgress: number
  setSetupProgress: (value: number) => void
  setPaywallIndex: (value: number) => void
  isCompactHeight: boolean
  isShortHeight: boolean
  showError: (message: string) => void
}

/**
 * Phase D D4 — onboarding wizard screen.
 * Pure presentation; orchestration state remains in `BjjAppInner`.
 */
export function OnboardingScreen({
  appState,
  updateAppState,
  updateProfile,
  refreshShellSnapshot,
  onboardingIndex,
  setOnboardingIndex,
  onboardingNameDraft,
  setOnboardingNameDraft,
  onboardingNameDirty,
  setOnboardingNameDirty,
  onboardingNameSentinel,
  onboardingNameInputUnlocked,
  setOnboardingNameInputUnlocked,
  setupProgress,
  setSetupProgress,
  setPaywallIndex,
  isCompactHeight,
  isShortHeight,
  showError,
}: OnboardingScreenProps) {
  const step = BJJ_ONBOARDING_STEPS[onboardingIndex]
  const onboardingBackdropVariant: ScreenBackdropVariant = step === 'welcome'
    ? 'onboarding-welcome'
    : step === 'mission'
      ? 'onboarding-mission'
      : step === 'name'
        ? 'onboarding-name'
        : step === 'discipline'
          ? 'onboarding-discipline'
          : step === 'experience'
            ? 'onboarding-experience'
            : step === 'content'
              ? 'onboarding-content'
              : step === 'pain-points'
                ? 'onboarding-challenges'
                : step === 'attribution'
                  ? 'onboarding-attribution'
                  : step === 'setup'
                    ? 'onboarding-setup'
                    : 'onboarding-ready'
  const onboardingActionLabel = step === 'ready' ? 'Welcome' : 'Continue'
  const onboardingActionDisabled =
    (step === 'name' && onboardingNameDraft.trim().length === 0)
    || (step === 'discipline' && !appState.profile.primaryDiscipline)
    || (step === 'experience' && !appState.profile.experienceLevel)
    || (step === 'content' && appState.profile.favoriteContentTypes.length === 0)
    || (step === 'pain-points' && appState.profile.biggestChallenges.length === 0)
    || (step === 'attribution' && !appState.profile.heardFrom)
    || (step === 'setup' && setupProgress < 100)
  const onboardingSkippableSteps: BjjOnboardingStep[] = ['content', 'pain-points', 'attribution']
  const canSkipOnboarding = onboardingSkippableSteps.includes(step)

  const onboardingTitleClass = isShortHeight ? 'text-[30px]' : isCompactHeight ? 'text-[36px]' : 'text-[42px]'
  const onboardingBodyClass = isShortHeight ? 'text-[16px] leading-6' : isCompactHeight ? 'text-[18px] leading-6' : 'text-[20px] leading-7'
  const onboardingPreviewWidthClass = isShortHeight ? 'w-[236px]' : isCompactHeight ? 'w-[248px]' : 'w-[264px]'
  const welcomeMediaHeightClass = isShortHeight ? 'h-[260px]' : isCompactHeight ? 'h-[304px]' : 'h-[min(52dvh,380px)]'
  const onboardingSectionGapClass = isShortHeight ? 'space-y-4' : isCompactHeight ? 'space-y-5' : 'space-y-6'
  const paywallBodyClass = isShortHeight ? 'text-[16px] leading-6' : isCompactHeight ? 'text-[18px] leading-6' : 'text-[20px] leading-7'

  const syncOnboardingProfile = async (updates: Partial<UserProfile>): Promise<UserProfile> => {
    const updatedProfile = await updateProfile(updates)
    updateAppState((previous) => ({
      ...previous,
      profile: {
        ...previous.profile,
        displayName: updatedProfile.displayName,
        username: updatedProfile.username,
        belt: updatedProfile.belt ?? previous.profile.belt,
        stripes: updatedProfile.stripes ?? previous.profile.stripes,
        primaryDiscipline: updatedProfile.primaryDiscipline ?? previous.profile.primaryDiscipline,
        experienceLevel: updatedProfile.experienceLevel ?? previous.profile.experienceLevel,
        favoriteContentTypes: updatedProfile.favoriteContentTypes ?? previous.profile.favoriteContentTypes,
        biggestChallenges: updatedProfile.biggestChallenges ?? previous.profile.biggestChallenges,
        heardFrom: updatedProfile.heardFrom ?? previous.profile.heardFrom,
        onboardingCompleted: updatedProfile.onboardingCompleted ?? previous.profile.onboardingCompleted,
      },
    }))
    return updatedProfile
  }

  const handleOnboardingContinue = async () => {
    if (step === 'setup') {
      if (setupProgress < 100) return
      setOnboardingIndex(BJJ_ONBOARDING_STEPS.indexOf('ready'))
      return
    }

    try {
      if (step === 'name') {
        const { error, value } = resolveOnboardingDisplayNameDraft(onboardingNameDraft)
        if (error) {
          showError(error)
          return
        }

        const slugFromName = slugifyUsername(value)
        const username = isAutoGeneratedUsername(appState.profile.username)
          ? (slugFromName || appState.profile.username)
          : appState.profile.username

        setOnboardingNameDraft(value)
        setOnboardingNameDirty(false)
        updateAppState((previous) => ({
          ...previous,
          profile: {
            ...previous.profile,
            displayName: value,
            username,
          },
        }))

        await syncOnboardingProfile({
          displayName: value,
          username,
        })
      }

      if (step === 'discipline') {
        await syncOnboardingProfile({
          primaryDiscipline: appState.profile.primaryDiscipline,
        })
      }

      if (step === 'experience') {
        await syncOnboardingProfile({
          experienceLevel: appState.profile.experienceLevel as UserProfile['experienceLevel'] | undefined,
          belt: appState.profile.belt,
          stripes: appState.profile.stripes,
        })
      }

      if (step === 'content') {
        await syncOnboardingProfile({
          favoriteContentTypes: appState.profile.favoriteContentTypes,
        })
      }

      if (step === 'pain-points') {
        await syncOnboardingProfile({
          biggestChallenges: appState.profile.biggestChallenges,
        })
      }

      if (step === 'attribution') {
        await syncOnboardingProfile({
          heardFrom: appState.profile.heardFrom,
        })
        setSetupProgress(27)
      }

      if (step === 'ready') {
        const updatedProfile = await syncOnboardingProfile({
          displayName: appState.profile.displayName.trim(),
          username: appState.profile.username.trim(),
          belt: appState.profile.belt,
          stripes: appState.profile.stripes,
          primaryDiscipline: appState.profile.primaryDiscipline,
          experienceLevel: appState.profile.experienceLevel as UserProfile['experienceLevel'] | undefined,
          favoriteContentTypes: appState.profile.favoriteContentTypes,
          heardFrom: appState.profile.heardFrom,
          biggestChallenges: appState.profile.biggestChallenges,
          onboardingCompleted: true,
        })
        updateAppState((previous) => ({
          ...previous,
          profile: {
            ...previous.profile,
            onboardingCompleted: updatedProfile.onboardingCompleted ?? true,
          },
        }))
        refreshShellSnapshot()
        setPaywallIndex(0)
        return
      }
    } catch (error) {
      showError(error instanceof Error ? error.message : 'Unable to persist onboarding progress')
      return
    }

    setOnboardingIndex((previous) => Math.min(previous + 1, BJJ_ONBOARDING_STEPS.length - 1))
  }

  const handleOnboardingSkip = async () => {
    try {
      const updatedProfile = await syncOnboardingProfile({
        displayName: appState.profile.displayName.trim(),
        username: appState.profile.username.trim(),
        belt: appState.profile.belt,
        stripes: appState.profile.stripes,
        primaryDiscipline: appState.profile.primaryDiscipline,
        experienceLevel: appState.profile.experienceLevel as UserProfile['experienceLevel'] | undefined,
        onboardingCompleted: true,
      })
      updateAppState((previous) => ({
        ...previous,
        profile: {
          ...previous.profile,
          onboardingCompleted: updatedProfile.onboardingCompleted ?? true,
        },
      }))
      refreshShellSnapshot()
      setPaywallIndex(0)
    } catch (error) {
      showError(error instanceof Error ? error.message : 'Unable to save your progress')
    }
  }

  return (
    <div className="relative h-[100dvh] overflow-hidden bg-[#04060a] text-white">
      <ScreenBackdrop variant={onboardingBackdropVariant} />
      <div className="relative mx-auto flex h-full w-full max-w-[430px] flex-col px-4 pb-[calc(env(safe-area-inset-bottom)+18px)] pt-[calc(env(safe-area-inset-top)+12px)]">
        <div className="flex items-center justify-between">
          <CircleIconButton
            onClick={() => setOnboardingIndex((previous) => Math.max(0, previous - 1))}
            className={cn(onboardingIndex === 0 && 'invisible')}
          >
            <ChevronLeft className="h-5 w-5" />
          </CircleIconButton>
          <ProgressDots count={BJJ_ONBOARDING_STEPS.length} active={onboardingIndex} />
          <div className="h-11 w-11" />
        </div>

        <div className="flex min-h-0 flex-1 flex-col pt-4">
          <div className="min-h-0 flex-1 overflow-y-auto pb-4">
          <p className="pb-2 text-center text-xs font-semibold uppercase tracking-[0.2em] text-white/45">
            Step {onboardingIndex + 1} of {BJJ_ONBOARDING_STEPS.length}
          </p>
          {step === 'welcome' && (
            <>
              <div className={cn('pt-2 text-center', onboardingSectionGapClass)}>
                <h1 className={cn(onboardingTitleClass, 'font-black leading-[0.95]')}>Congratulations!</h1>
                <p className={cn('mx-auto mt-3 max-w-[310px] text-white/70', onboardingBodyClass)}>
                  You’re joining the martial artists building a real technical memory, not winging it class to class.
                </p>
              </div>
              <div
                className={cn(
                  'relative mt-4 w-full',
                  welcomeMediaHeightClass,
                  'min-h-[220px]',
                )}
              >
                <div
                  className={cn(
                    'relative h-full w-full',
                    /* Feather the whole hero (image + letterbox) into the screen — WebKit needs both */
                    '[mask-image:radial-gradient(ellipse_102%_96%_at_50%_51%,#000_22%,#000_46%,transparent_88%)]',
                    '[-webkit-mask-image:radial-gradient(ellipse_102%_96%_at_50%_51%,#000_22%,#000_46%,transparent_88%)]',
                    '[mask-size:100%_100%]',
                    '[-webkit-mask-size:100%_100%]',
                    '[mask-position:center]',
                    '[-webkit-mask-position:center]',
                    '[mask-repeat:no-repeat]',
                    '[-webkit-mask-repeat:no-repeat]',
                  )}
                >
                  <Image
                    src="/loading-screen.png"
                    alt=""
                    fill
                    sizes="(max-width: 430px) 100vw, 430px"
                    className="object-contain object-center"
                    priority
                  />
                  <div
                    className="pointer-events-none absolute inset-0 bg-gradient-to-b from-[#04060a]/55 via-transparent to-[#04060a]/78"
                    aria-hidden
                  />
                  <div
                    className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_100%_92%_at_50%_50%,transparent_28%,rgba(4,6,10,0.35)_58%,rgba(4,6,10,0.92)_88%,rgba(4,6,10,1)_100%)]"
                    aria-hidden
                  />
                </div>
              </div>
            </>
          )}

          {step === 'mission' && (
            <>
              <div className="pt-2 text-center">
                <h2 className={cn(onboardingTitleClass, 'font-black leading-[0.97]')}>Train with purpose</h2>
                <p className={cn('mx-auto mt-3 max-w-[300px] text-white/68', onboardingBodyClass)}>
                  This is where grapplers, strikers, and combat athletes level up with a clear technical system.
                </p>
              </div>
              <ShellCard className={cn('mx-auto mt-4 rounded-[30px] p-3', onboardingPreviewWidthClass)}>
                <div className="rounded-[24px] border border-white/10 bg-black/70 p-3">
                  <div className="mb-3 flex items-center justify-between text-[11px] text-white/60">
                    <span>Weekly Focus</span>
                    <span>System Builder</span>
                  </div>
                  <div className="space-y-2.5">
                    {[
                      ['Capture class notes', 'Build memory after each session'],
                      ['Link techniques together', 'Create flow chains and counters'],
                      ['Review with intention', 'Stop random repetition'],
                    ].map(([title, body]) => (
                      <div key={title} className="rounded-[18px] border border-white/8 bg-white/4 p-2.5">
                        <p className="text-[15px] font-bold">{title}</p>
                        <p className="mt-1 text-[12px] text-white/58">{body}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </ShellCard>
            </>
          )}

          {step === 'discipline' && (
            <>
              <div className="pt-2 text-center">
                <h2 className={cn(onboardingTitleClass, 'font-black leading-[0.97]')}>What is your primary discipline?</h2>
                <p className={cn('mx-auto mt-3 max-w-[305px] text-white/68', onboardingBodyClass)}>
                  We tailor your feed and starter system to your base style.
                </p>
              </div>
              <div className="mt-6 space-y-1">
                {BJJ_PRIMARY_DISCIPLINE_OPTIONS.map((discipline) => (
                  <button
                    key={discipline}
                    type="button"
                    onClick={() => updateAppState((previous) => ({
                      ...previous,
                      profile: {
                        ...previous.profile,
                        primaryDiscipline: discipline,
                      },
                    }))}
                    className="flex w-full items-center justify-between border-b border-white/10 py-3.5 text-left"
                  >
                    <span className={cn('font-medium text-white/85', isCompactHeight ? 'text-[18px]' : 'text-[21px]')}>{discipline}</span>
                    <span className={cn('h-7 w-7 rounded-full border', appState.profile.primaryDiscipline === discipline ? 'border-[#4d7cff] bg-[#4d7cff]' : 'border-white/20')} />
                  </button>
                ))}
              </div>
            </>
          )}

          {step === 'name' && (
            <>
              <div className="pt-3 text-center">
                <h2 className={cn(onboardingTitleClass, 'font-black leading-[1]')}>What should we call you?</h2>
              </div>
              <div className="flex flex-1 flex-col justify-center">
                <input
                  {...createDisplayNameInputBehavior('onboarding', onboardingNameInputUnlocked, () => setOnboardingNameInputUnlocked(true))}
                  value={onboardingNameDraft}
                  onChange={(event) => {
                    const nextValue = event.target.value
                    const nativeEvent = event.nativeEvent as NativeInputLike
                    if (shouldIgnoreDisplayNameRefill({
                      sentinelValue: onboardingNameSentinel,
                      currentValue: onboardingNameDraft,
                      nextValue,
                      hasManualEdit: onboardingNameDirty,
                      inputType: nativeEvent.inputType,
                      isComposing: nativeEvent.isComposing,
                    })) {
                      return
                    }

                    setOnboardingNameDirty(true)
                    setOnboardingNameDraft(nextValue)
                  }}
                  placeholder="Enter your name"
                  className={cn(
                    'border-b border-white/20 bg-transparent px-1 py-3 font-semibold text-white placeholder:text-white/28 outline-none',
                    isShortHeight ? 'text-[22px]' : isCompactHeight ? 'text-[24px]' : 'text-[28px]',
                  )}
                />
              </div>
            </>
          )}

          {step === 'experience' && (
            <>
              <div className="pt-3 text-center">
                <h2 className={cn(isShortHeight ? 'text-[30px]' : isCompactHeight ? 'text-[34px]' : 'text-[40px]', 'font-black leading-[1]')}>Experience level</h2>
              </div>
              <div className="mt-6 space-y-1">
                {BJJ_EXPERIENCE_LEVEL_OPTIONS.map((experience) => (
                  <button
                    key={experience.id}
                    type="button"
                    onClick={() => updateAppState((previous) => ({
                      ...previous,
                      profile: {
                        ...previous.profile,
                        experienceLevel: experience.experienceLevel,
                        belt: experience.belt,
                        stripes: experience.stripes,
                      },
                    }))}
                    className="flex w-full items-center justify-between border-b border-white/10 py-3.5 text-left"
                  >
                    <span className={cn('font-medium text-white/85', isCompactHeight ? 'text-[18px]' : 'text-[21px]')}>{experience.label}</span>
                    <span className={cn('h-7 w-7 rounded-full border', appState.profile.experienceLevel === experience.experienceLevel ? 'border-[#4d7cff] bg-[#4d7cff]' : 'border-white/20')} />
                  </button>
                ))}
              </div>
            </>
          )}

          {step === 'content' && (
            <>
              <div className="pt-3 text-center">
                <h2 className={cn(isShortHeight ? 'text-[30px]' : isCompactHeight ? 'text-[34px]' : 'text-[40px]', 'font-black leading-[1]')}>Favorite content type</h2>
                <p className="mt-3 text-sm font-medium text-white/58">Select all that apply</p>
              </div>
              <div className="mt-6 space-y-1">
                {BJJ_FAVORITE_CONTENT_OPTIONS.map((contentType) => {
                  const selected = appState.profile.favoriteContentTypes.includes(contentType)
                  return (
                    <button
                      key={contentType}
                      type="button"
                      onClick={() => updateAppState((previous) => ({
                        ...previous,
                        profile: {
                          ...previous.profile,
                          favoriteContentTypes: selected
                            ? previous.profile.favoriteContentTypes.filter((entry) => entry !== contentType)
                            : [...previous.profile.favoriteContentTypes, contentType],
                        },
                      }))}
                      className="flex w-full items-center justify-between border-b border-white/10 py-3.5 text-left"
                    >
                      <span className={cn('max-w-[260px] font-medium text-white/85', isCompactHeight ? 'text-[18px]' : 'text-[21px]')}>{contentType}</span>
                      <span className={cn('flex h-7 w-7 items-center justify-center rounded-full border', selected ? 'border-[#4d7cff] bg-[#4d7cff]' : 'border-white/20')}>
                        {selected && <Check className="h-4 w-4" />}
                      </span>
                    </button>
                  )
                })}
              </div>
            </>
          )}

          {step === 'pain-points' && (
            <>
              <div className="pt-3 text-center">
                <h2 className={cn(isShortHeight ? 'text-[30px]' : isCompactHeight ? 'text-[34px]' : 'text-[40px]', 'font-black leading-[1]')}>What are your biggest challenges in martial arts?</h2>
                <p className="mt-3 text-sm font-medium text-white/58">Select all that apply</p>
              </div>
              <div className="mt-6 space-y-1">
                {BJJ_CHALLENGE_OPTIONS.map((challenge) => {
                  const selected = appState.profile.biggestChallenges.includes(challenge)
                  return (
                    <button
                      key={challenge}
                      type="button"
                      onClick={() => updateAppState((previous) => ({
                        ...previous,
                        profile: {
                          ...previous.profile,
                          biggestChallenges: selected
                            ? previous.profile.biggestChallenges.filter((entry) => entry !== challenge)
                            : [...previous.profile.biggestChallenges, challenge],
                        },
                      }))}
                      className="flex w-full items-center justify-between border-b border-white/10 py-3.5 text-left"
                    >
                      <span className={cn('max-w-[250px] font-medium text-white/85', isCompactHeight ? 'text-[18px]' : 'text-[21px]')}>{challenge}</span>
                      <span className={cn('flex h-7 w-7 items-center justify-center rounded-full border', selected ? 'border-[#4d7cff] bg-[#4d7cff]' : 'border-white/20')}>
                        {selected && <Check className="h-4 w-4" />}
                      </span>
                    </button>
                  )
                })}
              </div>
            </>
          )}

          {step === 'attribution' && (
            <>
              <div className="pt-3 text-center">
                <h2 className={cn(isShortHeight ? 'text-[30px]' : isCompactHeight ? 'text-[34px]' : 'text-[40px]', 'font-black leading-[1]')}>Where did you hear about us?</h2>
              </div>
              <div className="mt-6 space-y-1">
                {BJJ_HEARD_FROM_OPTIONS.map((source) => (
                  <button
                    key={source}
                    type="button"
                    onClick={() => updateAppState((previous) => ({
                      ...previous,
                      profile: {
                        ...previous.profile,
                        heardFrom: source,
                      },
                    }))}
                    className="flex w-full items-center justify-between border-b border-white/10 py-3.5 text-left"
                  >
                    <span className={cn('font-medium text-white/85', isCompactHeight ? 'text-[18px]' : 'text-[22px]')}>{source}</span>
                    <span className={cn('h-7 w-7 rounded-full border', appState.profile.heardFrom === source ? 'border-[#4d7cff] bg-[#4d7cff]' : 'border-white/20')} />
                  </button>
                ))}
              </div>
            </>
          )}

          {step === 'setup' && (
            <>
              <div className="flex-1 pt-6 text-center">
                <div className={cn(
                  'mx-auto flex items-center justify-center rounded-full border border-[#4d7cff]/25 bg-[#0d1732]/80 shadow-[0_0_0_18px_rgba(29,78,216,0.12)]',
                  isShortHeight ? 'h-24 w-24' : 'h-28 w-28',
                )}>
                  <div className="text-center">
                    <div className={cn(isCompactHeight ? 'text-[32px]' : 'text-[38px]', 'font-black')}>{setupProgress}%</div>
                  </div>
                </div>
                <div className="mt-7">
                  <div className="flex items-center justify-center gap-2 text-[#ffd84d]">
                    <Star className="h-5 w-5 fill-current" />
                    <Star className="h-5 w-5 fill-current" />
                    <Star className="h-5 w-5 fill-current" />
                    <Star className="h-5 w-5 fill-current" />
                    <Star className="h-5 w-5 fill-current" />
                  </div>
                  <p className="mt-3 text-sm font-semibold uppercase tracking-[0.24em] text-white/65">
                    Trusted by 30,000+ combat athletes
                  </p>
                </div>
                <h2 className={cn(isShortHeight ? 'mt-6 text-[30px]' : isCompactHeight ? 'mt-7 text-[34px]' : 'mt-8 text-[38px]', 'font-black leading-[1.02]')}>Setting up MatFlow…</h2>
                <p className={cn('mx-auto mt-3 max-w-[310px] text-white/58', paywallBodyClass)}>
                  Identifying growth opportunities and shaping your first technical system.
                </p>
                <div className="mx-auto mt-8 max-w-[360px] overflow-hidden rounded-[22px] border border-white/10 bg-white/8 text-left">
                  <div className="p-4">
                    <div className="flex items-center justify-between gap-3">
                      <p className="text-[16px] font-bold">KaitCox</p>
                      <div className="flex items-center gap-1 text-[#ffd84d]">
                        {Array.from({ length: 5 }, (_, index) => <Star key={index} className="h-4 w-4 fill-current" />)}
                      </div>
                    </div>
                    <p className="mt-3 text-[15px] leading-6 text-white/70">
                      “This is the best app out of the many I tried. I love that I can search moves by category and link techniques together.”
                    </p>
                  </div>
                </div>
              </div>
            </>
          )}

          {step === 'ready' && (
            <>
              <div className="flex-1 pt-6 text-center">
                <div className={cn(
                  'mx-auto relative overflow-hidden rounded-[24px] border border-white/10 bg-white/8',
                  isShortHeight ? 'h-20 w-20' : 'h-24 w-24',
                )}>
                  <Image src="/app-icon.png" alt="MatFlow icon" fill className="object-cover" />
                </div>
                <h2 className={cn(isShortHeight ? 'mt-6 text-[30px]' : isCompactHeight ? 'mt-7 text-[34px]' : 'mt-8 text-[42px]', 'font-black leading-[1]')}>
                  Everything is ready.
                </h2>
                <p className={cn('mx-auto mt-3 max-w-[310px] text-white/68', onboardingBodyClass)}>
                  Welcome! Your training system is set up and tailored for your progression.
                </p>

                <div className="mt-7 space-y-4 text-left">
                  {[
                    ['Log trainings & techniques', 'Make every class searchable.'],
                    ['Review your notes', 'Stop resetting every week.'],
                    ['Improve 2x faster', 'Use analytics and system thinking.'],
                  ].map(([title, body]) => (
                    <div key={title} className="flex items-start gap-4">
                      <div className="mt-1 flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/6">
                        <BookOpen className="h-5 w-5 text-white/80" />
                      </div>
                      <div>
                        <p className={cn(isCompactHeight ? 'text-[18px]' : 'text-[21px]', 'font-bold')}>{title}</p>
                        <p className="mt-1 text-[15px] text-white/52">{body}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}
          </div>

          <div className="shrink-0 bg-[linear-gradient(180deg,rgba(4,6,10,0),rgba(4,6,10,0.88)_22%,#04060a_100%)] pb-1 pt-2.5">
            <PrimaryButton onClick={() => void handleOnboardingContinue()} disabled={onboardingActionDisabled}>
              {onboardingActionLabel}
              <ChevronRight className="h-5 w-5" />
            </PrimaryButton>
            {canSkipOnboarding && (
              <button
                type="button"
                onClick={() => void handleOnboardingSkip()}
                className="mt-3 block w-full text-center text-sm font-semibold text-white/55"
              >
                I’ll set the rest up later
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
