-- Dropping tables not used by app runtime (src/) and not referenced by edge functions.
-- Also avoided dropping tables referenced by DB views/functions using best-effort scanning.
-- Generated by audit on 2026-04-13.

-- Break FK cycle between training_programs <-> training_program_versions.
alter table public.training_program_versions drop constraint if exists training_program_versions_program_id_fkey;
alter table public.training_programs drop constraint if exists training_programs_current_version_fkey;
alter table public.training_programs drop constraint if exists training_programs_original_version_fkey;

-- Drop candidates (children first where applicable).
DROP TABLE IF EXISTS public.activity_logs;
DROP TABLE IF EXISTS public.athlete_exercises;
DROP TABLE IF EXISTS public.athletes;
DROP TABLE IF EXISTS public.calendar_events;
DROP TABLE IF EXISTS public.comment_likes;
DROP TABLE IF EXISTS public.custom_workout_exercises;
DROP TABLE IF EXISTS public.custom_workouts;
DROP TABLE IF EXISTS public.exercise_completions;
DROP TABLE IF EXISTS public.exercise_events;
DROP TABLE IF EXISTS public.exercise_favorites;
DROP TABLE IF EXISTS public.exercise_recommendations;
DROP TABLE IF EXISTS public.feature_usage_counters;
DROP TABLE IF EXISTS public.fight_camp_plans;
DROP TABLE IF EXISTS public.frame_detections;
DROP TABLE IF EXISTS public.ingested_workout_routines;
DROP TABLE IF EXISTS public.learning_path_drills;
DROP TABLE IF EXISTS public.published_records;
DROP TABLE IF EXISTS public.moderation_queue;
DROP TABLE IF EXISTS public.extracted_signals;
DROP TABLE IF EXISTS public.routine_drills;
DROP TABLE IF EXISTS public.routines;
DROP TABLE IF EXISTS public.saved_drill_collection_items;
DROP TABLE IF EXISTS public.saved_drill_collections;
DROP TABLE IF EXISTS public.saved_library_items;
DROP TABLE IF EXISTS public.session_exercises;
DROP TABLE IF EXISTS public.session_log_weights;
DROP TABLE IF EXISTS public.session_logs;
DROP TABLE IF EXISTS public.program_sessions;
DROP TABLE IF EXISTS public.social_feed_events;
DROP TABLE IF EXISTS public.social_moderation_queue;
DROP TABLE IF EXISTS public.social_moderators;
DROP TABLE IF EXISTS public.social_negative_feedback;
DROP TABLE IF EXISTS public.social_playback_events;
DROP TABLE IF EXISTS public.social_post_feature_rollups;
DROP TABLE IF EXISTS public.social_post_topics;
DROP TABLE IF EXISTS public.social_rate_limits;
DROP TABLE IF EXISTS public.social_topics;
DROP TABLE IF EXISTS public.stripe_webhook_events;
DROP TABLE IF EXISTS public.training_program_state;
DROP TABLE IF EXISTS public.training_reminders;
DROP TABLE IF EXISTS public.training_set_logs;
DROP TABLE IF EXISTS public.training_session_entries;
DROP TABLE IF EXISTS public.transcript_segments;
DROP TABLE IF EXISTS public.user_learning_progress;
DROP TABLE IF EXISTS public.learning_paths;
DROP TABLE IF EXISTS public.user_recently_viewed;
DROP TABLE IF EXISTS public.drills;
DROP TABLE IF EXISTS public.video_ingests;
DROP TABLE IF EXISTS public.source_documents;
DROP TABLE IF EXISTS public.content_sources;
DROP TABLE IF EXISTS public.week_progress;
DROP TABLE IF EXISTS public.weekly_reviews;
DROP TABLE IF EXISTS public.workout_day_overrides;
DROP TABLE IF EXISTS public.workout_template_entries;
DROP TABLE IF EXISTS public.exercises;

-- Keep workout_templates because training_sessions has a foreign key to it.

-- Drop the previously-cyclic training program tables.
DROP TABLE IF EXISTS public.training_program_versions;
DROP TABLE IF EXISTS public.training_programs;

